Increment3
sherhan361/monitor pull request #3
Opened 2022-11-17 21:35 UTC by sherhan361

2022-11-18 22:53 UTC, avhitrov requested changes
Гонки в агенте, падение агента в отсутствие связи с сервером. Возможные гонки в сервере. Неверно увеличивается счетчик.

2022-11-18 22:53 UTC, avhitrov commented on cmd/agent/main.go
> +	go ReportSender(&m, reportInterval)
Оба процесса обращаются одновременно к одной структуре, один на чтение, второй на запись, и вызывают гонки. Это можно увидеть, скомпилировав агента с ключом `-race`.

2022-11-18 22:53 UTC, avhitrov commented on cmd/agent/main.go
> +				os.Exit(1)
Агент не должен падать, если сервер недоступен. Он вообще не должен останавливаться, пока не прилетит прерывание от системы. В случае, если не удалось отправить в свой черед метрики, необходимо сделать следующую попытку, накапливая счетчик итераций. Это касается всех os.Exit() в данной функции.

2022-11-18 22:53 UTC, avhitrov commented on internal/server/handler/routes.go
> +}
👍

2022-11-18 22:53 UTC, avhitrov commented on internal/server/handler/handlers.go
> +	if typ == "none" || name == "none" || value == "none" {
Не знаю, зачем идет проверка именно на это значение, но, в любом случае, проверка переменной typ здесь лишняя, так как список ее возможных значений проверяется в другом блоке.

2022-11-18 22:53 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +	return m.Gauges, m.Counters
После того, как эти мапы будут возвращены, лок с них будет снят. В момент отрисовки их значений вполне могут прилететь изменения в любую из них, и все равно возникнут гонки. Самое простое решение: в данной функции возвращать не сами мапы, а их копии.

2022-11-18 22:53 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +	if typ == "counter" {
Для этой пары if лучше подойдет 
switch typ {
case "counter":
case "gauge":
}

2022-11-18 22:53 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +		}
Если посмотреть на динамику изменения данного параметра, обнаружится, что он изменяется нелинейно. А должен при текущих условиях изменяться на 5 каждые 10 секунд. Причину предлагаю поискать.

2022-11-29 20:29 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +		}
Причина не устранена. Счетчик увеличивается нелинейно. Причина - в агенте. Поскольку инкремент есть и в сервере, и в агенте, агент должен накапливать свой счетчик проходов вплоть до момента успешной отправки. После успешной отправки счетчик необходимо сбрасывать.

2022-11-29 20:46 UTC, avhitrov requested changes
Есть замечание по защите мап о гонок, и счетчик все еще увеличивается нелинейно. Анализ в комментариях.

2022-11-29 20:46 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +	return gauges, counters
В этом случае все равно возможна гонка. Причина в том, что после завершения функции, блокировка снимается, и переданные мапы становятся уязвимы. Проще всего решить проблему, отдавая из функции не сами мапы, а их копии. Что-то вроде
```
gCopy := make(map[string]float64, len(m.Gauges))
for key, val := range m.Gauges {
    gCopy[key] = val
}
```

2022-11-29 20:46 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +	return gauges, counters
И да, только что увидел, что уже комментировал эту функцию. Дам чуть больше теории: мапа - строго ссылочная структура. Единственный способ ее скопировать - это создать еще одну мапу (не забыть указать размер от оригинала, чтобы избежать переаллокаций памяти) и перенести с помощью цикла. Возможно, функция `copy` умеет и мапы копировать, это надо поискать в доках.

Собственно, в примере все есть.

2022-11-29 20:46 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +	}
Здесь тоже можно switch typ {case-default}

2022-12-03 14:46 UTC, sherhan361 commented on internal/server/repository/memory/memory.go
> +		}
Добавил сброс счетчика в агенте после успешной отправки метрик.

2022-12-03 14:47 UTC, sherhan361 commented on internal/server/repository/memory/memory.go
> +	return gauges, counters
Судя по всему, copy делает поверхностное копирование. аналог питоновского deepcopy не нашел. Сделал по примеру выше.

2022-12-05 22:05 UTC, avhitrov approved these changes

2022-12-15 19:25 UTC, merged