Increment8
sherhan361/monitor pull request #8
Opened 2023-01-06 20:42 UTC by sherhan361

2023-01-12 22:45 UTC, avhitrov requested changes
1. Замечания в комментариях по коду.
2. Не реализован возврат JSON при вызове update
3. На сервере не работает прием запросов, сжатых gzip. (Проверить можно курлом: `curl -v -s --trace-ascii http_trace.log --data-binary @body.json.gz -H "Content-Type: application/json" -H "Content-Encoding: gzip" -X POST http://127.0.0.1:8080/update`)
4. При передаче STORE_INTERVAL=0 сервер должен сбрасывать данные на диск каждый раз, когда пишет в память. Это не реализовано. Рекомендую создать канал и, в случае установки флага в ноль, отправлять по нему данные из стораджа. Раннер бекапера модифицировать так, чтобы он читал либо канал от стораджа, либо таймер - тоже в зависимость от значения STORE_INTERVAL.

2023-01-12 22:45 UTC, avhitrov commented on internal/agent/handler/handlers.go
> +	type Metric struct {
Для поддержания единообразия в структуре передаваемых между сервисами данных, будет уместно вытащить описание общих структур в единое место, например, в internal/models/ или internal/views/
В этом случае, если необходимо что-то поменять в протоколе обмена, замена производится однократно.

2023-01-12 22:45 UTC, avhitrov commented on internal/server/handler/handlers.go
> +	}
```
r.Body.Close()
```

2023-01-12 22:45 UTC, avhitrov commented on internal/server/handler/handlers.go
> +	}
```
r.Body.Close()
```

2023-01-12 22:45 UTC, avhitrov commented on internal/server/handler/handlers.go
> +	w.WriteHeader(http.StatusOK)
В соответствии с ТЗ в ответ надо отправлять JSON той же структуры, что и на входе, но с актуальными данными. То есть для счетчика - текущее значение счетчика.

2023-01-14 08:59 UTC, sherhan361 commented on internal/server/handler/handlers.go
> +	}
сделал через defer r.Body.Close() чтобы не дублировать в ветках if err

2023-01-14 08:59 UTC, sherhan361 commented on internal/server/handler/handlers.go
> +	}
сделал через defer r.Body.Close() чтобы не дублировать в ветках if err

2023-02-11 13:28 UTC, avhitrov approved these changes
Все замеченные проблемы устранены, есть пара замечаний на оптимизацию, не сильно влияющих на функциональность.

2023-02-11 13:28 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +	content, err := ioutil.ReadFile(filename)
```suggestion
	content, err := os.ReadFile(filename)
```
ioutil deprecated

2023-02-11 13:28 UTC, avhitrov commented on internal/server/repository/memory/memory.go
> +	defer m.mutex.RUnlock()
По ощущениям, блокировать сторадж здесь нет необходимости, так как GetAll выдает копию данных. Блокировку файла осуществляет сама система. Но можно сделать блокировку на уровне приложения. тогда GetAll отправляется в самый верх (чтобы не вступать в конфликт с записью файла), подготовку данных можно делать смело без мьютекса, открытие и запись саккумулировать внизу функции и на него ставить полноценный Lock-Unlock.

Кроме того, на файловые операции можно завести собственный мьютекс.

2023-02-11 20:23 UTC, merged